

export const questions: {question: string, answer1: string, answer2: string, answer3: string, answer4: string, correctAnswer: Array<string>  }[]= [
    {question: "You are a project owner and need your co-worker to deploy a new version of your application to App Engine. You want to follow Google’s recommended practices. Which IAM roles should you grant your co-worker?",
    answer1: "Project Editor",
    answer2: "App Engine Service Admin",
    answer3: "App Engine Deployer",
    answer4: "App Engine Code Viewer",
    correctAnswer: ["App Engine Deployer"]
    },
    {question: "Your company has reserved a monthly budget for your project. You want to be informed automatically of your project spend so that you can take action when you approach the limit. What should you do?",
    answer1: "Link a credit card with a monthly limit equal to your budget.",
    answer2: "Create a budget alert for 50%, 90%, and 100% of your total monthly budget.",
    answer3: " In App Engine Settings, set a daily budget at the rate of 1/30 of your monthly budget.",
    answer4: "In the GCP Console, configure billing export to BigQuery. Create a saved view that queries your total spend.",
    correctAnswer: ["Create a budget alert for 50%, 90%, and 100% of your total monthly budget."]
    },
    {question: "You have a project using BigQuery. You want to list all BigQuery jobs for that project. You want to set this project as the default for the bq command-line tool. What should you do?",
    answer1: "Use 'gcloud config set project' to set the default project.",
    answer2: "Use bq config set project' to set the default project.",
    answer3: " Use 'gcloud generate config-url' to generate a URL to the Google Cloud Platform Console to set the default project.",
    answer4: "Use 'bq generate config-url' to generate a URL to the Google Cloud Platform Console to set the default project.",
    correctAnswer: [ "Use 'gcloud config set project' to set the default project."]
    },
    {question: "Your project has all its Compute Engine resources in the europe-west1 region. You want to set europe-west1 as the default region for gcloud commands. What should you do?",
    answer1: "Use Cloud Shell instead of the command line interface of your device. Launch Cloud Shell after you navigate to a resource in the europe-west1 region. The europe-west1 region will automatically become the default region.",
    answer2: "Use 'gcloud config set compute/zone europe-west1' to set the default region for future gcloud commands.",
    answer3: "Use 'gcloud config set compute/region europe-west1' to set the default region for future gcloud commands.",
    answer4: "Create a VPN from on-premises to a subnet in europe-west1, and use that connection when executing gcloud commands.",
    correctAnswer: ["Use 'gcloud config set compute/region europe-west1' to set the default region for future gcloud commands."]
    },
    {question: "You developed a new application for App Engine and are ready to deploy it to production. You need to estimate the costs of running your application on Google Cloud Platform as accurately as possible. What should you do?",
    answer1: "Create a YAML file with the expected usage. Pass this file to the 'gcloud app estimate' command to get an accurate estimation.",
    answer2: "Multiply the costs of your application when it was in development by the number of expected users to get an accurate estimation.",
    answer3: "Use the pricing calculator for App Engine to get an accurate estimation of the expected charges.",
    answer4: " Create a ticket with Google Cloud Billing Support to get an accurate estimation.",
    correctAnswer: ["Use the pricing calculator for App Engine to get an accurate estimation of the expected charges."]
    },
    {question: "Your company processes high volumes of IoT data that are time-stamped. The total data volume can be several petabytes. The data needs to be written and changed at a high speed. You want to use the most performant storage option for your data. Which product should you use?",
    answer1: "Cloud Datastore",
    answer2: "Cloud Storage",
    answer3: "Cloud Bigtable",
    answer4: "BigQuery",
    correctAnswer: ["Cloud Bigtable"]
    },
    {question: "Your application has a large international audience and runs stateless virtual machines within a managed instance group across multiple locations. One feature of the application lets users upload files and share them with other users. Files must be available for 30 days; after that, they are removed from the system entirely. Which storage solution should you choose?",
    answer1: "A Cloud Datastore database.",
    answer2: "A multi-regional Cloud Storage bucket.",
    answer3: "Persistent SSD on virtual machine instances.",
    answer4: "A managed instance group of Filestore servers.",
    correctAnswer: ["A multi-regional Cloud Storage bucket."]
    },
    {question: "You have a definition for an instance template that contains a web application. You are asked to deploy the application so that it can scale based on the HTTP traffic it receives. What should you do?",
    answer1: "Create a VM from the instance template. Create a custom image from the VM’s disk. Export the image to Cloud Storage. Create an HTTP load balancer and add the Cloud Storage bucket as its backend service.",
    answer2: "Create a VM from the instance template. Create an App Engine application in Automatic Scaling mode that forwards all traffic to the VM.",
    answer3: "Create a managed instance group based on the instance template. Configure autoscaling based on HTTP traffic and configure the instance group as the backend service of an HTTP load balancer.",
    answer4: "Create the necessary amount of instances required for peak user traffic based on the instance template. Create an unmanaged instance group and add the instances to that instance group. Configure the instance group as the Backend Service of an HTTP load balancer.",
    correctAnswer: ["Create a managed instance group based on the instance template. Configure autoscaling based on HTTP traffic and configure the instance group as the backend service of an HTTP load balancer."]
    },
    {question: "You are creating a Kubernetes Engine cluster to deploy multiple pods inside the cluster. All container logs must be stored in BigQuery for later analysis. You want to follow Google-recommended practices. Which two approaches can you take?",
    answer1: "Turn on Stackdriver Logging during the Kubernetes Engine cluster creation.",
    answer2: "Turn on Stackdriver Monitoring during the Kubernetes Engine cluster creation.",
    answer3: "Use the Stackdriver Logging export feature to create a sink to BigQuery. Specify a filter expression to export log records related to your Kubernetes Engine cluster only.",
    answer4: "Use the Stackdriver Logging export feature to create a sink to Cloud Storage. Create a Cloud Dataflow job that imports log files from Cloud Storage to BigQuery.",
    correctAnswer: ["Turn on Stackdriver Logging during the Kubernetes Engine cluster creation.", "Use the Stackdriver Logging export feature to create a sink to BigQuery. Specify a filter expression to export log records related to your Kubernetes Engine cluster only."]
    },
    {question: "You need to create a new Kubernetes Cluster on Google Cloud Platform that can autoscale the number of worker nodes. What should you do?",
    answer1: "Create a cluster on Kubernetes Engine and enable autoscaling on Kubernetes Engine.",
    answer2: "Create a cluster on Kubernetes Engine and enable autoscaling on the instance group of the cluster.",
    answer3: "Configure a Compute Engine instance as a worker and add it to an unmanaged instance group. Add a load balancer to the instance group and rely on the load balancer to create additional Compute Engine instances when needed.",
    answer4: "Create Compute Engine instances for the workers and the master, and install Kubernetes. Rely on Kubernetes to create additional Compute Engine instances when needed.",
    correctAnswer: ["Create a cluster on Kubernetes Engine and enable autoscaling on Kubernetes Engine."]
    },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // },
    // {question: "",
    // answer1: "",
    // answer2: "",
    // answer3: "",
    // answer4: "",
    // correctAnswer: []
    // }
]